{'application':{'type':'Application',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'bgMin',
          'title':u'Parliament: parliamentary procedure helper',
          'size':(1024, 768),
          'backgroundColor':(118, 152, 154),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileStartOver',
                   'label':'Start Over (clear all)',
                  },
                  {'type':'MenuItem',
                   'name':'menuLoadRuleset',
                   'label':'Load ruleset',
                  },
                  {'type':'MenuItem',
                   'name':'menuLoadMeetingState',
                   'label':'Load complete meeting state',
                  },
                  {'type':'MenuItem',
                   'name':'menuSave',
                   'label':u'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuSaveAs',
                   'label':u'&Save as...',
                  },
                  {'type':'MenuItem',
                   'name':'menuSaveMeetingMinutesAsFile',
                   'label':'Write meeting minutes as text file',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuNavigation',
             'label':'Navigation',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuNavigationGoBack',
                   'label':'Go Back\tAlt+B',
                  },
                  {'type':'MenuItem',
                   'name':'menuNavigationGoFwd',
                   'label':'Go Forward\tAlt+W',
                  },
                  {'type':'MenuItem',
                   'name':'menuNavigationMotionAdopted',
                   'label':'Motion Adopted\tAlt+P',
                  },
                  {'type':'MenuItem',
                   'name':'menuNavigationMotionRejected',
                   'label':'Motion Rejected\tAlt+F',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuView',
             'label':u'View',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuViewDisplayOnlyWindow',
                   'label':u'Display "view only" window',
                   'checkable':1,
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'ImageButton', 
    'name':'BackBtn', 
    'position':(234, 4), 
    'size':(65, 50), 
    'backgroundColor':(215, 215, 215), 
    'border':'none', 
    'file':'backArrow.jpg',
    },

{'type':'ImageButton', 
    'name':'FwdBtn', 
    'position':(324, 4), 
    'size':(65, 50), 
    'backgroundColor':(215, 215, 215), 
    'border':'none', 
    'file':'fwdArrow.jpg',
    },

{'type':'Tree', 
    'name':'initiativeTree', 
    'position':(679, 5), 
    'size':(300, 120), 
    'backgroundColor':(255, 255, 255), 
    'userdata':(309, 220), 
    },

{'type':'MultiColumnList', 
    'name':'list', 
    'position':(4, 57), 
    'size':(600, 536), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':[], 
    'font':{'faceName': u'Sans', 'size': 13}, 
    'items':[], 
    'maxColumns':20, 
    'rules':0, 
    },

{'type':'StaticText', 
    'name':'motionRules', 
    'position':(679, 130), 
    'backgroundColor':(118, 152, 154), 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 16}, 
    'foregroundColor':(255, 255, 0), 
    },

{'type':'StaticText', 
    'name':'moverLabel', 
    'position':(624, 165), 
    'backgroundColor':(118, 152, 154), 
    'text':'Mover:', 
    },

{'type':'TextField', 
    'name':'moverField', 
    'position':(679, 160), 
    'size':(300, -1), 
    },

{'type':'StaticText', 
    'name':'targetLabel', 
    'position':(623, 200), 
    'backgroundColor':(118, 152, 154),
    'text':'Target:', 
    },

{'type':'TextField', 
    'name':'TargetText', 
    'position':(679, 195), 
    'size':(300, -1), 
    'editable':False, 
    },

{'type':'Button', 
    'name':'TargetChangeButton', 
    'position':(995, 195), 
    'size':(74, -1), 
    'backgroundColor':(118, 152, 154),
    'label':'Change', 
    'userdata':(136, 153, 155), 
    },

{'type':'StaticText', 
    'name':'textLabel', 
    'position':(636, 235), 
    'backgroundColor':(118, 152, 154), 
    'text':'Text:', 
    },

{'type':'TextArea', 
    'name':'actionInfo', 
    'position':(679, 230), 
    'size':(300, 240), 
    'editable':False, 
    'enabled':True, 
    },

{'type':'StaticText', 
    'name':'affirmativeVotesLabel', 
    'position':(248, 644), 
    'backgroundColor':(118, 152, 154), 
    'text':'Affirmative', 
    },

{'type':'TextField', 
    'name':'affirmativeVotes', 
    'position':(260, 615), 
    'size':(43, -1), 
    },

{'type':'StaticText', 
    'name':'negativeVotesLabel', 
    'position':(325, 644), 
    'backgroundColor':(118, 152, 154), 
    'text':'Negative', 
    },

{'type':'TextField', 
    'name':'negativeVotes', 
    'position':(330, 615), 
    'size':(44, -1), 
    },

{'type':'Button', 
    'name':'recordVoteButton', 
    'position':(260, 671), 
    'size':(113, 38), 
    'label':'Record Vote', 
    },

{'type':'Button', 
    'name':'AdoptedBtn', 
    'position':(4, 613), 
    'size':(165, 78), 
    'backgroundColor':(129, 213, 103), 
    'font':{'family': 'sansSerif', 'size': 16}, 
    'label':'Adopted', 
    },

{'type':'Button', 
    'name':'RejectedBtn', 
    'position':(450, 614), 
    'size':(153, 79), 
    'backgroundColor':(234, 91, 80), 
    'font':{'family': 'sansSerif', 'size': 16}, 
    'label':'Rejected', 
    },

{'type':'CheckBox', 
    'name':'IgnoreRulesCheckBox', 
    'position':(4, 709), 
    'size':(127, 23), 
    'backgroundColor':(118, 152, 154),
    'label':'Ignore the rules', 
    },

{'type':'CheckBox', 
    'name':'ShowUnimplementedCheckbox', 
    'position':(4, 739), 
    'size':(250, -1), 
    'backgroundColor':(118, 152, 154), 
    'label':'Show unimplemented motions', 
    },

{'type':'StaticText', 
    'name':'historyLabel', 
    'position':(619, 485), 
    'backgroundColor':(118, 152, 154), 
    'text':'History:', 
    },

{'type':'TextArea', 
    'name':'history', 
    'position':(679, 480), 
    'size':(300, 280), 
    'editable':False, 
    },

] # end components
} # end background
] # end backgrounds
} }
