{'application':{'type':'Application',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'bgMin',
          'title':u'Parliament: parliamentary procedure helper',
          'size':(1280, 1024),
          'backgroundColor':(192, 192, 192),
          'visible':0,

         'components': [

{'type':'StaticText', 
    'name':'moverLabel', 
    'position':(-1, -1), 
    'backgroundColor':(192, 192, 192), 
    'text':'StaticText', 
    'visible':False, 
    },

{'type':'TextField', 
    'name':'moverField', 
    'position':(-1, -1), 
    'enabled':False, 
    'visible':False, 
    },

{'type':'TextField', 
    'name':'TargetText', 
    'position':(-1, -1), 
    'enabled':True, 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'targetLabel', 
    'position':(-1, -1), 
    'backgroundColor':(192, 192, 192), 
    'text':'StaticText', 
    'visible':False, 
    },

{'type':'TextArea', 
    'name':'history', 
    'position':(-1, -1), 
    'size':(0,0), 
    'editable':False, 
    'enabled':False, 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'TreeLabel', 
    'position':(4, 8), 
    'backgroundColor':(192, 192, 192), 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 24}, 
    'text':'pending questions', 
    },

{'type':'Tree', 
    'name':'initiativeTree', 
    'position':(4, 58), 
    'size':(560, 220), 
    'backgroundColor':(255, 255, 255), 
    'enabled':True, 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 24}, 
    'userdata':(309, 220), 
    },

{'type':'StaticText', 
    'name':'motionRules', 
    'position':(4, 286), 
    'backgroundColor':(192, 192, 192), 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 24}, 
    'text':'', 
    },

{'type':'StaticText', 
    'name':'detailsLabel', 
    'position':(4, 326), 
    'backgroundColor':(192, 192, 192), 
    'enabled':True, 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 24}, 
    'text':'question text', 
    },

{'type':'TextArea', 
    'name':'actionInfo', 
    'position':(4, 366), 
    'size':(560, 644), 
    'editable':False, 
    'enabled':True, 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 24}, 
    'visible':True, 
    },


{'type':'MultiColumnList', 
    'name':'list', 
    'position':(598, 4), 
    'size':(588, 1016), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':[], 
    'enabled':True, 
    'font':{'faceName': u'Sans', 'size': 24}, 
    'items':[], 
    'maxColumns':20, 
    'rules':0, 
    },

] # end components
} # end background
] # end backgrounds
} }
